### PR TITLE
fix: mongo to 2

### PR DESCRIPTION
**Pull request by fengthedroid**
screen shot 2015-10-21 at 6 02 31 pm

Merge only after anduril updates to mongo node 2

### CODE REVIEW

**Comment by shanejonas** [comment]
:+1:

**Comment by stryderjzw** [comment]
who's fred?

**Comment by fengthedroid** [comment]
The chinese guy I hired for all my coding. Duh.

**Comment by stryderjzw** [comment]
Can I hire him? He does good work.

**Comment by Pyrolistical** [comment]
:+1:

**Comment by Pyrolistical** [comment]
No, get @fengthedroid to keep hiring more people.  We don't want to manage people if @fengthedroid can do it all.  Its a multiplier affect

**Pull request merged**
